import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import AuthContext from "@/context/AuthContext";
import SwrConfigContext from "@/context/SwrConfigContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col w-full max-w-screen-2xl mx-auto">
          <AuthContext>
            <Navbar />
            <SwrConfigContext>{children}</SwrConfigContext>
          </AuthContext>
        </main>
      </body>
    </html>
  );
}
